### PR TITLE
Add test file to figure out println! formatting stack usage

### PR DESCRIPTION
**Pull request by dhylands**
I get these results:
```
x
1
1.2
1.2.3
1.2.3.4
1.2
1.2 3.4
1.2 3.4 5.6
1.2 3.4 5.6 7.8
    null:     0
println!:   648
   int 1:   176
   int 2:    32
   int 3:    40
   int 4:    40
 float 1:  1464
 float 2:    48
 float 3:    40
 float 4:   112
```

### CODE REVIEW

**Comment by fabricedesre** [comment]
Cool! You could also add something to format floats, like: println!("{:.*}", 2, 1.234567);

**Comment by dhylands** [comment]
The current code uses {:.1} but I'll try adding what you suggested and see how it performs

**Comment by dhylands** [comment]
Wow. I added these 2 functions:

```
fn test1f2() {
    let num1: f64 = 1.234;
    println!("{:.*}", 2, num1);
}

fn test2f2() {
    let num1: f64 = 1.234;
    let num2: f64 = 2.345;
    println!("{:.*} {:.*}", 2, num1, 2, num2);
}
```

test1f2 required 1504 bytes
test2f2 required an additional 724 bytes
Adding one more only needed 80 extra bytes.

**Comment by dhylands** [comment]
So that means test2f2 needed a total of 2900 bytes of stack space.

**Comment by dhylands** [comment]
Closing old PRs

**Pull request closed without merging**
