### PR TITLE
Update cc3200 cfg

### PR DESCRIPTION
**Pull request by dhylands**
I updated cc3200.cfg like this to work on my Ubuntu 16.04 machine

### CODE REVIEW

**Comment by fabricedesre** [comment]
Which version of opencd are you using? I could only get things to work with 0.7.0

**Comment by dhylands** [comment]
I was using 0.9.0 (with the attached change to cc3200.cfg)

**Comment by dhylands** [comment]
And this is what I get when I run it:

```
2010 >openocd -f cc3200.cfg 
Open On-Chip Debugger 0.9.0 (2015-09-02-10:42)
Licensed under GNU GPL v2
For bug reports, read
    http://openocd.org/doc/doxygen/bugs.html
adapter speed: 1000 kHz
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
cc3200_dbginit
Info : clock speed 1000 kHz
Info : JTAG tap: cc3200.jrc tap/device found: 0x0b97c02f (mfg: 0x017, part: 0xb97c, ver: 0x0)
Info : JTAG tap: cc3200.dap enabled
Info : cc3200.cpu: hardware has 6 breakpoints, 4 watchpoints
```

and I have to hit Control-C right here.

**Comment by dhylands** [comment]
This version of cc3200.cfg is appropriate for use with openocd v0.8 and 0.9 (they replaced ft2232 with ftdi in 0.8.0)

**Comment by fabricedesre** [comment]
Just tested with the standard openocd 0.9.0 from ubuntu, and that works fine. Let's take that instead of a custom 0.7.0 build.

**Pull request merged**
